[package]
name = "pda-test-client"
version = "0.0.0"
edition = "2018"

[dependencies]
solana-sdk = "1.8.5"
solana-client = "1.8.5"

vault = { path = "../program", features = [ "no-entrypoint" ] }
solana-program = "1.8.5"
borsh = "0.9.1"
anyhow = "1.0.48"
