[package]
name = "sol_logging"
version = "0.1.0"
edition = "2018"

[features]
no-entrypoint = []

[dependencies]
borsh = "0.9.1"
solana-program = "1.8.5"
thiserror = "1.0.30"
num-derive = "0.3.3"
num-traits = "0.2.14"

[dev-dependencies]
solana-sdk = "1.8.5"
solana-program-test = "1.8.5"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
